#!/system/bin/sh

busybox mount -o remount,ro,noatime,nodiratime,noauto_da_alloc,barrier=0,nobh /system
busybox mount -o remount,noatime,nodiratime,noauto_da_alloc,nodev,barrier=0,nobh /cache
busybox mount -o remount,noatime,nodiratime,noauto_da_alloc,nodev,barrier=0,nobh /data
